// Generated by JetlinkKit/Scripts/make_pins.py from the Python in this
// checkout. Do not edit: change the Python, run the script, commit both.
// docs/conformance.md says what each value pins and how.

/// The constants the Swift server shares with the comma's Python, as the
/// Python defines them. Each Swift constant that means the same thing is
/// tested against these, and the Python tests that this file is current.
public enum Pinned {
  /// jetlink.__version__
  public static let productVersion: String = "0.8.1"
  /// jetlink.protocol.MAGIC
  public static let magic: UInt32 = 0x4B4E_4C4A
  /// jetlink.protocol.VERSION
  public static let protocolVersion: UInt16 = 3
  /// jetlink.protocol.HEADER_SIZE
  public static let headerSize: Int = 32
  /// jetlink.protocol.PACKET_MULTIPLE
  public static let packetMultiple: Int = 512
  /// jetlink.protocol.GADGET_TX_ALIGN
  public static let gadgetTxAlign: Int = 16384
  /// jetlink.protocol.INFER_REQ_SIZE
  public static let inferReqSize: Int = 8
  /// jetlink.protocol.INFER_RESP_SIZE
  public static let inferRespSize: Int = 20
  /// jetlink.transport.base.MAX_MESSAGE
  public static let maxMessage: Int = 16777216
  /// jetlink.transport.tcp.DEFAULT_PORT
  public static let defaultPort: UInt16 = 5599
  /// jetlink.protocol.Msg
  public static let messageTypes: [(name: String, value: UInt16)] = [
    ("HELLO_REQ", 1),
    ("HELLO_RESP", 2),
    ("ENGINE_REQ", 3),
    ("ENGINE_RESP", 4),
    ("UPLOAD_CHUNK", 5),
    ("UPLOAD_DONE", 6),
    ("PROGRESS", 7),
    ("INFER_REQ", 8),
    ("INFER_RESP", 9),
    ("STATE_REQ", 12),
    ("STATE_RESP", 13),
    ("ERROR", 14),
    ("PING", 15),
    ("PONG", 16),
    ("SHUTDOWN_REQ", 17),
    ("SHUTDOWN_RESP", 18),
    ("LEAVE", 19),
  ]
  /// jetlink.protocol.Flag
  public static let flags: [(name: String, value: UInt32)] = [
    ("RESET_QUEUES", 1),
    ("WANT_STATE", 2),
    ("WANT_HIDDEN", 4),
    ("PADDED", 128),
  ]
  /// jetlink.protocol.Status
  public static let statuses: [(name: String, value: UInt32)] = [
    ("OK", 0),
    ("NOT_READY", 1),
    ("BAD_SHAPE", 2),
    ("INFER_FAILED", 3),
    ("NOT_FINITE", 4),
  ]
  /// jetlink.protocol.USB_VID
  public static let usbVendorID: UInt16 = 0x1209
  /// jetlink.protocol.USB_PID
  public static let usbProductID: UInt16 = 0x0001
  /// jetlink.protocol.USB_VENDOR_CLASS
  public static let usbVendorClass: [UInt8] = [0xFF, 0xFF, 0xFF]
  /// jetlink.protocol.USB_MAX_PACKET
  public static let usbMaxPacket: Int = 1024
  /// jetlink.transport.base.USB_MEDIA
  public static let usbSpeedMedia: [String: String] = [
    "super-speed-plus": "usb3",
    "super-speed": "usb3",
    "high-speed": "usb2",
    "full-speed": "usb1",
    "low-speed": "usb1",
  ]
  /// jetlink.transport.tcp.CABLE_ADDRESS
  public static let cableAddress: String = "192.168.60.1"
  /// jetlink.protocol.LEAVE_REASONS
  public static let leaveReasons: [String] = ["behind", "lost", "stopped", "provisioned"]
  /// jetlink.spec.MODEL_RUN_FREQ
  public static let modelRunFrequency: Int = 20
  /// jetlink.spec.MODEL_CONTEXT_FREQ
  public static let modelContextFrequency: Int = 5
  /// jetlink.spec.DEFAULT_FRAME_SKIP
  public static let defaultFrameSkip: Int = 4
  /// jetlink.spec.CHUNK
  public static let uploadChunk: Int = 4194304
  /// JetlinkKit/Scripts/fixture-pins.txt: onnxruntime
  public static let onnxruntimeVersion: String = "1.29.0"
}
