#!/usr/bin/env python3
"""
Copyright (c) 2026-, Zeph Leggett.

This file is part of jetlink and is licensed under the MIT License.
See the LICENSE file in the root directory for more details.

Writes JetlinkKit/Sources/JetlinkKit/Pinned.swift: the constants the Swift and
Python implementations must agree on, as the Python defines them.

  .venv/bin/python JetlinkKit/Scripts/make_pins.py [--out FILE]

Python is the source. The Swift constants (Wire.version, Wire.maxMessage,
CoreMLBackend.prepareVersion and the rest) are tested against Pinned in the
Swift suites, and tests/test_conformance.py fails when the committed file is
not what this script writes now. docs/conformance.md has the whole story.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
# This checkout's jetlink and tests, ahead of any jetlink the environment has
# installed: a venv's editable install can point at another checkout.
sys.path.insert(0, str(ROOT))
OUT = ROOT / 'JetlinkKit' / 'Sources' / 'JetlinkKit' / 'Pinned.swift'


def values() -> list[tuple[str, str, str, str]]:
  """(swift name, swift type, swift literal, where the Python keeps it)."""
  from jetlink import protocol as P
  from jetlink.server import control
  from jetlink.server import session
  from jetlink.server.backends import ort
  from jetlink.spec import CHUNK, DEFAULT_FRAME_SKIP, MODEL_CONTEXT_FREQ, MODEL_RUN_FREQ
  from jetlink.transport import base, tcp, usbbulk

  def hex32(v: int) -> str:
    text = f'{v:08X}'
    return f'0x{text[:4]}_{text[4:]}'

  def pairs(enum) -> str:
    rows = ''.join(f'    ("{m.name}", {int(m)}),\n' for m in enum)
    return f'[\n{rows}  ]'

  return [
    ('magic', 'UInt32', hex32(P.MAGIC), 'protocol.MAGIC'),
    ('protocolVersion', 'UInt16', str(P.VERSION), 'protocol.VERSION'),
    ('headerSize', 'Int', str(P.HEADER_SIZE), 'protocol.HEADER_SIZE'),
    ('packetMultiple', 'Int', str(P.PACKET_MULTIPLE), 'protocol.PACKET_MULTIPLE'),
    ('gadgetTxAlign', 'Int', str(P.GADGET_TX_ALIGN), 'protocol.GADGET_TX_ALIGN'),
    ('inferReqSize', 'Int', str(P.INFER_REQ_SIZE), 'protocol.INFER_REQ_SIZE'),
    ('inferRespSize', 'Int', str(P.INFER_RESP_SIZE), 'protocol.INFER_RESP_SIZE'),
    ('maxMessage', 'Int', str(base.MAX_MESSAGE), 'transport.base.MAX_MESSAGE'),
    ('defaultPort', 'UInt16', str(tcp.DEFAULT_PORT), 'transport.tcp.DEFAULT_PORT'),
    ('messageTypes', '[(name: String, value: UInt16)]', pairs(P.Msg), 'protocol.Msg'),
    ('flags', '[(name: String, value: UInt32)]', pairs(P.Flag), 'protocol.Flag'),
    ('statuses', '[(name: String, value: UInt32)]', pairs(P.Status), 'protocol.Status'),
    ('usbVendorID', 'UInt16', f'0x{usbbulk.JETLINK_VID:04X}', 'transport.usbbulk.JETLINK_VID'),
    ('usbProductID', 'UInt16', f'0x{usbbulk.JETLINK_PID:04X}', 'transport.usbbulk.JETLINK_PID'),
    ('usbVendorClass', '[UInt8]', '[' + ', '.join(f'0x{v:02X}' for v in usbbulk.VENDOR_CLASS) + ']',
     'transport.usbbulk.VENDOR_CLASS'),
    ('usbMaxPacket', 'Int', str(usbbulk.MAX_PACKET), 'transport.usbbulk.MAX_PACKET'),
    ('linkMedia', '[String]', '[' + ', '.join(f'"{m}"' for m in base.LINK_MEDIA) + ']', 'transport.base.LINK_MEDIA'),
    ('usbSpeedMedia', '[String: String]',
     '[\n' + ''.join(f'    "{k}": "{v}",\n' for k, v in base.USB_MEDIA.items()) + '  ]', 'transport.base.USB_MEDIA'),
    ('cableAddress', 'String', f'"{tcp.CABLE_ADDRESS}"', 'transport.tcp.CABLE_ADDRESS'),
    ('usbReadChunk', 'Int', str(usbbulk.READ_CHUNK), 'transport.usbbulk.READ_CHUNK'),
    ('modelRunFrequency', 'Int', str(MODEL_RUN_FREQ), 'spec.MODEL_RUN_FREQ'),
    ('modelContextFrequency', 'Int', str(MODEL_CONTEXT_FREQ), 'spec.MODEL_CONTEXT_FREQ'),
    ('defaultFrameSkip', 'Int', str(DEFAULT_FRAME_SKIP), 'spec.DEFAULT_FRAME_SKIP'),
    ('uploadChunk', 'Int', str(CHUNK), 'spec.CHUNK'),
    ('slowFrameUs', 'Int', str(session.SLOW_FRAME_US), 'server.session.SLOW_FRAME_US'),
    ('controlProtocol', 'Int', str(control.PROTOCOL), 'server.control.PROTOCOL'),
    ('prepareVersion', 'Int', str(ort.PREPARE_VERSION), 'server.backends.ort.PREPARE_VERSION'),
    ('onnxruntimeVersion', 'String', f'"{ort.APPLE_ONNXRUNTIME}"', 'server.backends.ort.APPLE_ONNXRUNTIME'),
  ]


def render() -> str:
  lines = [
    '// Generated by JetlinkKit/Scripts/make_pins.py from the Python in this',
    '// checkout. Do not edit: change the Python, run the script, commit both.',
    '// docs/conformance.md says what each value pins and how.',
    '',
    '/// The constants the Swift and the Python implementations have to agree on,',
    '/// as the Python defines them. Each Swift constant that means the same thing',
    '/// is tested against these, and the Python tests that this file is current.',
    'public enum Pinned {',
  ]
  for name, kind, literal, source in values():
    lines.append(f'  /// jetlink.{source}')
    lines.append(f'  public static let {name}: {kind} = {literal}')
  lines.append('}')
  return '\n'.join(lines) + '\n'


def generate(out: Path = OUT) -> None:
  out.parent.mkdir(parents=True, exist_ok=True)
  out.write_text(render())


if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Writes the constants Swift pins to the Python.')
  parser.add_argument('--out', type=Path, default=OUT, help='the Swift file to write (default: Pinned.swift in JetlinkKit)')
  generate(parser.parse_args().out)
